import {
  Assignment,
  AssignmentSubmission,
  Quiz,
  QuizAttempt,
  Course,
  StudentPerformance,
  CourseAnalytics,
  User,
} from '@/types/lms';

export const mockCourses: Course[] = [
  { id: 'c1', name: 'Introduction to Web Development', code: 'WEB101', instructor: 'Dr. Sarah Chen', studentCount: 45 },
  { id: 'c2', name: 'Advanced React Patterns', code: 'REACT301', instructor: 'Prof. Michael Brown', studentCount: 32 },
  { id: 'c3', name: 'Data Structures & Algorithms', code: 'DSA201', instructor: 'Dr. Emily Watson', studentCount: 58 },
  { id: 'c4', name: 'Machine Learning Fundamentals', code: 'ML101', instructor: 'Dr. James Liu', studentCount: 40 },
  { id: 'c5', name: 'Cloud Computing with AWS', code: 'AWS201', instructor: 'Prof. Lisa Anderson', studentCount: 35 },
];

export const mockAssignments: Assignment[] = [
  {
    id: 'a1',
    title: 'Build a Responsive Portfolio Website',
    description: 'Create a fully responsive portfolio website showcasing your projects and skills.',
    instructions: '<p>Create a modern, responsive portfolio website that includes:</p><ul><li>A hero section with your introduction</li><li>A projects gallery with at least 3 projects</li><li>A contact form</li><li>Responsive design for mobile, tablet, and desktop</li></ul>',
    courseId: 'c1',
    courseName: 'Introduction to Web Development',
    type: 'individual',
    submissionTypes: ['file', 'repo', 'url'],
    gradingMethod: 'rubric',
    maxScore: 100,
    rubric: [
      { id: 'r1', name: 'Design & Layout', description: 'Visual appeal and user experience', maxPoints: 25, weight: 25 },
      { id: 'r2', name: 'Responsiveness', description: 'Works well on all screen sizes', maxPoints: 25, weight: 25 },
      { id: 'r3', name: 'Code Quality', description: 'Clean, organized, and well-commented code', maxPoints: 25, weight: 25 },
      { id: 'r4', name: 'Functionality', description: 'All features work correctly', maxPoints: 25, weight: 25 },
    ],
    dueDate: '2025-01-15T23:59:00Z',
    lateSubmissionAllowed: true,
    latePenalty: 10,
    allowResubmission: true,
    maxResubmissions: 2,
    createdAt: '2024-12-20T10:00:00Z',
    createdBy: 'Dr. Sarah Chen',
    totalSubmissions: 38,
    gradedSubmissions: 25,
  },
  {
    id: 'a2',
    title: 'Implement a Custom React Hook',
    description: 'Create a reusable custom hook for handling form state and validation.',
    instructions: '<p>Develop a custom React hook called <code>useForm</code> that:</p><ul><li>Manages form field values</li><li>Handles validation with custom rules</li><li>Provides error messages</li><li>Supports async validation</li></ul>',
    courseId: 'c2',
    courseName: 'Advanced React Patterns',
    type: 'individual',
    submissionTypes: ['repo'],
    gradingMethod: 'score',
    maxScore: 50,
    dueDate: '2025-01-10T23:59:00Z',
    lateSubmissionAllowed: false,
    allowResubmission: false,
    createdAt: '2024-12-18T14:00:00Z',
    createdBy: 'Prof. Michael Brown',
    totalSubmissions: 28,
    gradedSubmissions: 28,
  },
  {
    id: 'a3',
    title: 'Binary Search Tree Implementation',
    description: 'Implement a complete binary search tree with all standard operations.',
    instructions: '<p>Implement a Binary Search Tree class with the following methods:</p><ul><li>insert(value)</li><li>search(value)</li><li>delete(value)</li><li>inOrderTraversal()</li><li>preOrderTraversal()</li><li>postOrderTraversal()</li></ul>',
    courseId: 'c3',
    courseName: 'Data Structures & Algorithms',
    type: 'individual',
    submissionTypes: ['file', 'repo'],
    gradingMethod: 'score',
    maxScore: 100,
    dueDate: '2025-01-20T23:59:00Z',
    lateSubmissionAllowed: true,
    latePenalty: 15,
    allowResubmission: true,
    maxResubmissions: 1,
    createdAt: '2024-12-22T09:00:00Z',
    createdBy: 'Dr. Emily Watson',
    totalSubmissions: 42,
    gradedSubmissions: 15,
  },
  {
    id: 'a4',
    title: 'Team Project: E-Commerce Dashboard',
    description: 'Build a comprehensive e-commerce analytics dashboard as a team.',
    instructions: '<p>As a team, create an e-commerce dashboard that displays:</p><ul><li>Sales metrics and charts</li><li>Customer analytics</li><li>Product performance</li><li>Real-time updates</li></ul>',
    courseId: 'c2',
    courseName: 'Advanced React Patterns',
    type: 'group',
    submissionTypes: ['repo', 'url'],
    gradingMethod: 'rubric',
    maxScore: 200,
    rubric: [
      { id: 'r1', name: 'Technical Implementation', description: 'Code quality and architecture', maxPoints: 50, weight: 25 },
      { id: 'r2', name: 'UI/UX Design', description: 'Visual design and user experience', maxPoints: 50, weight: 25 },
      { id: 'r3', name: 'Features', description: 'Completeness of required features', maxPoints: 50, weight: 25 },
      { id: 'r4', name: 'Teamwork', description: 'Collaboration and documentation', maxPoints: 50, weight: 25 },
    ],
    dueDate: '2025-02-01T23:59:00Z',
    lateSubmissionAllowed: false,
    allowResubmission: false,
    createdAt: '2024-12-25T11:00:00Z',
    createdBy: 'Prof. Michael Brown',
    totalSubmissions: 8,
    gradedSubmissions: 0,
  },
];

export const mockSubmissions: AssignmentSubmission[] = [
  {
    id: 's1',
    assignmentId: 'a1',
    assignmentTitle: 'Build a Responsive Portfolio Website',
    studentId: 'st1',
    studentName: 'Alex Johnson',
    studentEmail: 'alex.johnson@university.edu',
    studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    status: 'graded',
    submittedAt: '2025-01-14T18:30:00Z',
    files: [
      { id: 'f1', name: 'portfolio.zip', type: 'application/zip', size: 2500000, url: '#' },
    ],
    repoUrl: 'https://github.com/alexj/portfolio',
    demoUrl: 'https://alexj-portfolio.vercel.app',
    grade: 92,
    rubricGrades: [
      { criteriaId: 'r1', score: 23, feedback: 'Excellent visual design with great attention to detail.' },
      { criteriaId: 'r2', score: 25, feedback: 'Perfect responsiveness across all devices.' },
      { criteriaId: 'r3', score: 22, feedback: 'Clean code, could use more comments.' },
      { criteriaId: 'r4', score: 22, feedback: 'All features working smoothly.' },
    ],
    feedback: 'Outstanding work! Your portfolio demonstrates strong design skills and technical proficiency.',
    gradedBy: 'Dr. Sarah Chen',
    gradedAt: '2025-01-16T10:00:00Z',
    version: 1,
  },
  {
    id: 's2',
    assignmentId: 'a1',
    assignmentTitle: 'Build a Responsive Portfolio Website',
    studentId: 'st2',
    studentName: 'Emma Williams',
    studentEmail: 'emma.williams@university.edu',
    studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    status: 'submitted',
    submittedAt: '2025-01-15T22:45:00Z',
    repoUrl: 'https://github.com/emmaw/my-portfolio',
    demoUrl: 'https://emma-portfolio.netlify.app',
    version: 2,
  },
  {
    id: 's3',
    assignmentId: 'a1',
    assignmentTitle: 'Build a Responsive Portfolio Website',
    studentId: 'st3',
    studentName: 'James Chen',
    studentEmail: 'james.chen@university.edu',
    studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    status: 'late',
    submittedAt: '2025-01-16T08:30:00Z',
    files: [
      { id: 'f2', name: 'portfolio-project.zip', type: 'application/zip', size: 3200000, url: '#' },
    ],
    version: 1,
  },
  {
    id: 's4',
    assignmentId: 'a2',
    assignmentTitle: 'Implement a Custom React Hook',
    studentId: 'st1',
    studentName: 'Alex Johnson',
    studentEmail: 'alex.johnson@university.edu',
    studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    status: 'graded',
    submittedAt: '2025-01-09T20:00:00Z',
    repoUrl: 'https://github.com/alexj/use-form-hook',
    grade: 48,
    feedback: 'Excellent implementation with great TypeScript types!',
    gradedBy: 'Prof. Michael Brown',
    gradedAt: '2025-01-11T14:00:00Z',
    version: 1,
  },
  {
    id: 's5',
    assignmentId: 'a3',
    assignmentTitle: 'Binary Search Tree Implementation',
    studentId: 'st4',
    studentName: 'Sophie Martin',
    studentEmail: 'sophie.martin@university.edu',
    studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie',
    status: 'pending',
    version: 0,
  },
  {
    id: 's6',
    assignmentId: 'a3',
    assignmentTitle: 'Binary Search Tree Implementation',
    studentId: 'st5',
    studentName: 'Ryan Thompson',
    studentEmail: 'ryan.thompson@university.edu',
    studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ryan',
    status: 'submitted',
    submittedAt: '2025-01-19T16:20:00Z',
    files: [
      { id: 'f3', name: 'bst.py', type: 'text/x-python', size: 8500, url: '#' },
      { id: 'f4', name: 'test_bst.py', type: 'text/x-python', size: 4200, url: '#' },
    ],
    repoUrl: 'https://github.com/ryant/bst-implementation',
    version: 1,
    plagiarismScore: 12,
  },
];

export const mockQuizzes: Quiz[] = [
  {
    id: 'q1',
    title: 'HTML & CSS Fundamentals',
    description: 'Test your knowledge of HTML5 and CSS3 basics.',
    courseId: 'c1',
    courseName: 'Introduction to Web Development',
    questions: [
      {
        id: 'qq1',
        type: 'multiple_choice',
        question: 'Which HTML5 element is used to define navigation links?',
        options: ['<navigation>', '<nav>', '<links>', '<menu>'],
        correctAnswer: '<nav>',
        points: 10,
        explanation: 'The <nav> element represents a section of the page intended for navigation links.',
      },
      {
        id: 'qq2',
        type: 'true_false',
        question: 'CSS Grid and Flexbox can be used together in the same layout.',
        correctAnswer: 'true',
        points: 10,
        explanation: 'Yes, Grid and Flexbox serve different purposes and can be combined effectively.',
      },
      {
        id: 'qq3',
        type: 'short_answer',
        question: 'What CSS property is used to change the stacking order of elements?',
        correctAnswer: 'z-index',
        points: 15,
      },
      {
        id: 'qq4',
        type: 'multiple_choice',
        question: 'Which CSS unit is relative to the font-size of the root element?',
        options: ['em', 'rem', 'px', 'vh'],
        correctAnswer: 'rem',
        points: 10,
      },
    ],
    timeLimit: 30,
    dueDate: '2025-01-18T23:59:00Z',
    shuffleQuestions: true,
    showResults: true,
    maxAttempts: 2,
    createdAt: '2024-12-20T10:00:00Z',
    createdBy: 'Dr. Sarah Chen',
    totalAttempts: 89,
    averageScore: 78,
  },
  {
    id: 'q2',
    title: 'React Hooks Deep Dive',
    description: 'Advanced quiz on React hooks and their use cases.',
    courseId: 'c2',
    courseName: 'Advanced React Patterns',
    questions: [
      {
        id: 'qq5',
        type: 'multiple_choice',
        question: 'Which hook should be used for side effects that need cleanup?',
        options: ['useState', 'useEffect', 'useMemo', 'useCallback'],
        correctAnswer: 'useEffect',
        points: 15,
      },
      {
        id: 'qq6',
        type: 'short_answer',
        question: 'What is the dependency array in useEffect used for?',
        correctAnswer: 'To control when the effect runs',
        points: 20,
      },
      {
        id: 'qq7',
        type: 'true_false',
        question: 'useCallback returns a memoized version of the callback function.',
        correctAnswer: 'true',
        points: 10,
      },
    ],
    timeLimit: 20,
    dueDate: '2025-01-12T23:59:00Z',
    shuffleQuestions: false,
    showResults: true,
    maxAttempts: 1,
    createdAt: '2024-12-18T14:00:00Z',
    createdBy: 'Prof. Michael Brown',
    totalAttempts: 32,
    averageScore: 85,
  },
  {
    id: 'q3',
    title: 'Algorithm Complexity',
    description: 'Test your understanding of Big O notation and algorithm analysis.',
    courseId: 'c3',
    courseName: 'Data Structures & Algorithms',
    questions: [
      {
        id: 'qq8',
        type: 'multiple_choice',
        question: 'What is the time complexity of binary search?',
        options: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'],
        correctAnswer: 'O(log n)',
        points: 15,
      },
      {
        id: 'qq9',
        type: 'multiple_choice',
        question: 'Which sorting algorithm has the best average-case time complexity?',
        options: ['Bubble Sort', 'Quick Sort', 'Selection Sort', 'Insertion Sort'],
        correctAnswer: 'Quick Sort',
        points: 15,
      },
      {
        id: 'qq10',
        type: 'short_answer',
        question: 'What is the space complexity of a recursive Fibonacci function without memoization?',
        correctAnswer: 'O(n)',
        points: 20,
      },
    ],
    timeLimit: 25,
    dueDate: '2025-01-25T23:59:00Z',
    shuffleQuestions: true,
    showResults: false,
    maxAttempts: 1,
    createdAt: '2024-12-22T09:00:00Z',
    createdBy: 'Dr. Emily Watson',
    totalAttempts: 45,
    averageScore: 72,
  },
];

export const mockQuizAttempts: QuizAttempt[] = [
  {
    id: 'qa1',
    quizId: 'q1',
    quizTitle: 'HTML & CSS Fundamentals',
    studentId: 'st1',
    studentName: 'Alex Johnson',
    studentEmail: 'alex.johnson@university.edu',
    studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    answers: [
      { questionId: 'qq1', answer: '<nav>', isCorrect: true, score: 10 },
      { questionId: 'qq2', answer: 'true', isCorrect: true, score: 10 },
      { questionId: 'qq3', answer: 'z-index', isCorrect: true, score: 15 },
      { questionId: 'qq4', answer: 'rem', isCorrect: true, score: 10 },
    ],
    startedAt: '2025-01-17T14:00:00Z',
    completedAt: '2025-01-17T14:22:00Z',
    score: 45,
    maxScore: 45,
    status: 'graded',
    feedback: 'Perfect score! Excellent understanding of HTML & CSS.',
  },
  {
    id: 'qa2',
    quizId: 'q1',
    quizTitle: 'HTML & CSS Fundamentals',
    studentId: 'st2',
    studentName: 'Emma Williams',
    studentEmail: 'emma.williams@university.edu',
    studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    answers: [
      { questionId: 'qq1', answer: '<nav>', isCorrect: true, score: 10 },
      { questionId: 'qq2', answer: 'false', isCorrect: false, score: 0 },
      { questionId: 'qq3', answer: 'position', isCorrect: false, score: 0 },
      { questionId: 'qq4', answer: 'rem', isCorrect: true, score: 10 },
    ],
    startedAt: '2025-01-17T15:30:00Z',
    completedAt: '2025-01-17T15:55:00Z',
    score: 20,
    maxScore: 45,
    status: 'graded',
  },
];

export const mockStudentPerformance: StudentPerformance[] = [
  {
    studentId: 'st1',
    studentName: 'Alex Johnson',
    studentEmail: 'alex.johnson@university.edu',
    studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    averageScore: 92,
    completionRate: 100,
    submittedCount: 5,
    totalAssignments: 5,
    trend: 'up',
    scores: [
      { date: '2024-12-01', score: 85 },
      { date: '2024-12-15', score: 88 },
      { date: '2025-01-01', score: 92 },
      { date: '2025-01-10', score: 96 },
    ],
  },
  {
    studentId: 'st2',
    studentName: 'Emma Williams',
    studentEmail: 'emma.williams@university.edu',
    studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    averageScore: 78,
    completionRate: 80,
    submittedCount: 4,
    totalAssignments: 5,
    trend: 'stable',
    scores: [
      { date: '2024-12-01', score: 75 },
      { date: '2024-12-15', score: 78 },
      { date: '2025-01-01', score: 80 },
      { date: '2025-01-10', score: 79 },
    ],
  },
  {
    studentId: 'st3',
    studentName: 'James Chen',
    studentEmail: 'james.chen@university.edu',
    studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    averageScore: 65,
    completionRate: 60,
    submittedCount: 3,
    totalAssignments: 5,
    trend: 'down',
    scores: [
      { date: '2024-12-01', score: 72 },
      { date: '2024-12-15', score: 68 },
      { date: '2025-01-01', score: 65 },
      { date: '2025-01-10', score: 55 },
    ],
  },
];

export const mockCourseAnalytics: CourseAnalytics[] = [
  {
    courseId: 'c1',
    courseName: 'Introduction to Web Development',
    averageScore: 82,
    submissionRate: 92,
    gradeDistribution: [
      { grade: 'A', count: 15 },
      { grade: 'B', count: 18 },
      { grade: 'C', count: 8 },
      { grade: 'D', count: 3 },
      { grade: 'F', count: 1 },
    ],
    assignmentDifficulty: [
      { assignmentId: 'a1', title: 'Portfolio Website', avgScore: 85 },
      { assignmentId: 'a2', title: 'CSS Grid Layout', avgScore: 78 },
    ],
  },
  {
    courseId: 'c2',
    courseName: 'Advanced React Patterns',
    averageScore: 88,
    submissionRate: 95,
    gradeDistribution: [
      { grade: 'A', count: 12 },
      { grade: 'B', count: 14 },
      { grade: 'C', count: 5 },
      { grade: 'D', count: 1 },
      { grade: 'F', count: 0 },
    ],
    assignmentDifficulty: [
      { assignmentId: 'a3', title: 'Custom Hook', avgScore: 90 },
      { assignmentId: 'a4', title: 'Team Dashboard', avgScore: 85 },
    ],
  },
];

export const mockCurrentUser: User = {
  id: 'u1',
  name: 'Dr. Sarah Chen',
  email: 'sarah.chen@university.edu',
  role: 'tutor',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
};
